# Generated by Django 4.1 on 2022-09-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderplaced",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
